name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Generate Docker image tag.
        run: |
          mjv=$(cat CMakeLists.txt | grep 'PROJECT_VERSION_MAJOR' | sed 's/.*PROJECT_VERSION_MAJOR \(.*\))$/\1/')
          minv=$(cat CMakeLists.txt | grep 'PROJECT_VERSION_MINOR' | sed 's/.*PROJECT_VERSION_MINOR \(.*\))$/\1/')
          pv=$(cat CMakeLists.txt | grep 'PROJECT_VERSION_PATCH' | sed 's/.*PROJECT_VERSION_PATCH \(.*\))$/\1/')

          echo "IMAGE_TAG=${mjv}.${minv}.${pv}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --no-cache -t rminol/frame-logger:latest .

      - name: Push Docker Image
        run: |
          docker tag rminol/frame-logger:latest rminol/frame-logger:${IMAGE_TAG}
          docker push rminol/frame-logger:latest
          docker push rminol/frame-logger:${IMAGE_TAG}
